### ISSUE TITLE
BUG 34 (2) В выпадающем списке "Виды спорта", первый сверху вид спорта всегда синий, даже если не в фокусе.

### ISSUE THREAD

**Issue by AleksandrSokolov1992** [Sports-Guide/sports-guide-frontend#55]
Actual Result
Окружение: Chrome, 1920х1080, версия 119 и выше
Приоритет: Низкий
Шаги

1. Зайти на сайт [https://sports-map.ru/](https://sports-map.ru/api/categories/)

2. Кликнуть па кнопку "Войти"

3. Авторизироваться под пользователем логин rastafari1992@gmail.com, пароль Qwerty15

4. Нажать кнопку "Войти"

5. Кликнуть на кнопку 'Добавить площадку"

6. Кликнуть на поле с выпадающим списком "Виды спорта"

ОР Поле футбол не выделено бледно-голубым
ФР Поле футбол выделено синим

**Comment by MaxLogvinov** [comment]
Пофикшено
