### ISSUE TITLE
BUG v2 При снятии фокуса, не отжимая ЛКМ и выходя за рамки окна "Войти" -  окно закрывается 

### ISSUE THREAD

**Issue by AleksandrSokolov1992** [Sports-Guide/sports-guide-frontend#65]
Actual result
Окружение: Chrome, 1920х1080, версия 119 и выше
Приоритет: Низкий
Шаги

1. Зайти на сайт https://sports-map.ru/
2. Кликнуть на кнопку "Войти"
3. Ввести в поле пароль "123456"
4. Скопировать пароль, зажав ЛКМ и протянув выходя за рамки поля
5. Отпустить ЛКМ

ОР Окно "Вход" - не закрылось
ФР Окно "Вход" - закрылось

Скринкаст:

https://github.com/Sports-Guide/sports-guide-frontend/assets/154006575/69ee7632-47e1-4465-8e02-874a4e4dc2b4

**Comment by MaxLogvinov** [comment]
По логике так и закладывалось, что окно будет закрываться при клике вне попапа
